### ISSUE TITLE
[arm] cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by KalleVuorjoki** [wunderio/silta-cli#46]
Runs fine on linux, but on M1 mac I get following error
```.local/bin/silta: cannot execute binary file: Exec format error```

any ideas?

**Comment by Jancis** [comment]
Mac OS version differs due to app signing requirement, here's how to install cli via brew - https://github.com/wunderio/silta-cli?tab=readme-ov-file#macos

**Comment by KalleVuorjoki** [comment]
Thanks.
